/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "secondary-fixed-dim": "#bfd8e9",
          "on-secondary": "#3d5563",
          "surface-tint": "#81ecff",
          "outline": "#737679",
          "error-container": "#9f0519",
          "surface": "#0b0e12",
          "on-secondary-fixed": "#2a4250",
          "secondary": "#cde6f7",
          "on-tertiary-fixed-variant": "#003971",
          "on-primary": "#005762",
          "surface-container-highest": "#22262b",
          "primary-container": "#00e3fd",
          "tertiary-fixed": "#80b2ff",
          "surface-bright": "#282d31",
          "primary-fixed": "#00e3fd",
          "inverse-primary": "#006976",
          "on-primary-fixed-variant": "#005762",
          "on-error": "#490006",
          "on-surface-variant": "#a9abaf",
          "tertiary-dim": "#5c9ffc",
          "surface-container-lowest": "#000000",
          "outline-variant": "#45484c",
          "secondary-fixed": "#cde6f7",
          "on-background": "#f8f9fe",
          "tertiary-fixed-dim": "#65a4ff",
          "error-dim": "#d7383b",
          "inverse-on-surface": "#535559",
          "surface-container": "#161a1e",
          "on-tertiary": "#002a55",
          "error": "#ff716c",
          "on-surface": "#f8f9fe",
          "primary-dim": "#00d4ec",
          "surface-container-high": "#1c2024",
          "tertiary-container": "#599cf9",
          "on-error-container": "#ffa8a3",
          "surface-container-low": "#101417",
          "secondary-container": "#324a57",
          "on-primary-fixed": "#003840",
          "on-primary-container": "#004d57",
          "on-tertiary-fixed": "#001835",
          "primary": "#81ecff",
          "background": "#0b0e12",
          "on-secondary-fixed-variant": "#475f6d",
          "surface-dim": "#0b0e12",
          "surface-variant": "#22262b",
          "secondary-dim": "#bfd8e9",
          "tertiary": "#70aaff",
          "primary-fixed-dim": "#00d4ec",
          "inverse-surface": "#f8f9fe",
          "on-tertiary-container": "#001d3f",
          "on-secondary-container": "#bbd4e4"
      },
      "borderRadius": {
          "DEFAULT": "0px",
          "lg": "0px",
          "xl": "0px",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Space Grotesk", "sans-serif"],
          "body": ["Manrope", "sans-serif"],
          "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
